import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { StoreProvider } from "./store";
import Head from 'next/head';
import { AppRouterCacheProvider } from '@mui/material-nextjs/v13-appRouter';
import { LoginStatusClientSide } from "./components/login-status";


if (!new class { x: any }().hasOwnProperty('x')) throw new Error('Transpiler is not configured correctly');


const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <Head>
        <meta name="viewport" content="initial-scale=1, width=device-width" />
      </Head>
      <body className={inter.className}>
        <LoginStatusClientSide/>
        <StoreProvider>
           <AppRouterCacheProvider>
            {children}
          </AppRouterCacheProvider>
        </StoreProvider>        
      </body>
    </html>
  );
}
